[Spark unit test] Adjust tolerance for test_xqa, test_logits_processor (#2828)
<!-- .github/pull_request_template.md -->

## 📌 Description

Adjust tolerance slightly to avoid unnecessary noise in Spark unit
testing.

I found these spark failures in these pipelines:
https://gitlab-master.nvidia.com/dl/flashinfer/flashinfer-ci/-/jobs/284263159,
https://gitlab-master.nvidia.com/dl/flashinfer/flashinfer-ci/-/jobs/284263158
```
=================================== FAILURES ===================================
E   AssertionError: Batch validation failed: Total 4096 elements, only 4052 (98.9%) meet tolerance criteria, require at least 99.0%
    assert 0.9892578125 >= 0.99
/tmp/flashinfer/tests/attention/test_xqa.py:463: AssertionError: Batch validation failed: Total 4096 elements, only 4052 (98.9%) meet tolerance criteria, require at least 99.0%
=========================== short test summary info ============================
FAILED tests/attention/test_xqa.py::test_xqa[True-1.0-True-0.5-HND-8-128-16-4-1-512-True-input_type1-True-False]
= 1 failed, 41119 passed, 1 xfailed, 10239 xpassed, 1 warning in 591.93s (0:09:51) =
❌ FAILED: tests/attention/test_xqa.py
==========================================
```

```
=================================== FAILURES ===================================
E   AssertionError: Too many differences: 2.02%
    assert 0.020202020202020204 < 0.02
/tmp/flashinfer/tests/utils/test_logits_processor.py:828: AssertionError: Too many differences: 2.02%
=========================== short test summary info ============================
FAILED tests/utils/test_logits_processor.py::TestLogitsPipeVsSamplingOps::test_sequential_probs_topk_topp_sample[0.1-128256-99]
====== 1 failed, 590 passed, 12 skipped, 1 warning in 1621.97s (0:27:01) =======
❌ FAILED: tests/utils/test_logits_processor.py
==========================================
```

## 🔍 Related Issues

<!-- Link any related issues here -->

## 🚀 Pull Request Checklist

Thank you for contributing to FlashInfer! Before we review your pull
request, please make sure the following items are complete.

### ✅ Pre-commit Checks

- [x] I have installed `pre-commit` by running `pip install pre-commit`
(or used your preferred method).
- [x] I have installed the hooks with `pre-commit install`.
- [x] I have run the hooks manually with `pre-commit run --all-files`
and fixed any reported issues.

> If you are unsure about how to set up `pre-commit`, see [the
pre-commit documentation](https://pre-commit.com/).

## 🧪 Tests

- [x] Tests have been added or updated as needed.
- [x] All tests are passing (`unittest`, etc.).

## Reviewer Notes

<!-- Optional: anything you'd like reviewers to focus on, concerns, etc.
-->